require.config
	deps:['main']
	paths:
		"jquery":"../libs/jquery/default/jquery"
		"underscore":"../libs/underscore/default/underscore"
		"backbone":"../libs/backbone/default/backbone"
		"bootstrap":"../libs/bootstrap/default/bootstrap"
		"text":"../libs/requirejs/plugins/text/text"
		"domReady":"../libs/requirejs/plugins/domReady/domReady"
		"modernizr":"../libs/modernizr/default/modernizr"
		"sidr":"../libs/sidr/default/jquery.sidr.min"
		"templates":"../tpl"
		"css":"../libs/requirejs/plugins/css/css"
		"root":"../"
		"libs":"../libs"
	shim:
		'backbone':
			deps:['jquery','underscore']
			exports:'Backbone'
		'underscore':
			exports:'_'
		'bootstrap':
			deps:['jquery']
		'sidr':
			deps:['jquery']
			